############################################
#      CONFIGURATION FOR ALL PROJECTS      #
############################################

# Note:  if you make changes to this file you are potentially altering
#   every project
#   It is recommended that you override only those parts that you need in
#   the project specific configuration files (projects/name/config/config.yml)
#   For example, you will need a solr_core name for each project
#   You may place the settings under development / production if the environments
#   differ, but you may put things outside of development / production if the
#   setting will be the same for both.  The script locations below are applied to
#   both development and production, but if you need to run a different script for
#   each environment, you could copy whichever script override you need into
#   development and production

default:
  ##################################################################
  #   Ignore These Unless If You Really Want to Change Some Logs   #
  ##################################################################

  log_old_number: 4   # number of log files before beginning to erase
  log_size: 1024000   # size of log file in bytes
  log_level: Logger::WARN  # could change to INFO for more detail

  #################
  #   Threading   #
  #################

  # for less powerful servers set this to 5 or 10
  # more powerful servers can probably handle 40 or 50
  threads: 20

  ########################
  #   Script Locations   #
  ########################

  # formats to solr transformation locations
  tei_solr_xsl: scripts/xslt/cdrh_to_solr/solr_transform_tei.xsl
  vra_solr_xsl: scripts/xslt/cdrh_to_solr/solr_transform_vra.xsl
  dc_solr_xsl: scripts/xslt/cdrh_to_solr/solr_transform_dc.xsl
  csv_solr_ruby: scripts/ruby/csv_to_solr.rb
  # formats to html snippets transformation locations
  tei_html_xsl: scripts/xslt/cdrh_tei_to_html/tei.p5.xsl
  vra_html_xsl:
  dc_html_xsl: scripts/xslt/cdrh_dc_to_html/dublin_core_to_html.xsl
  csv_html_ruby: scripts/ruby/csv_to_html.rb

###################
#   Development   #
###################

development:
  # solr information
  solr_path: http://server.unl.edu:port/solr/
  solr_core: name_of_core

  # NOTE! If you are altering ANY of the xsl_params you must
  #   copy over ALL of them to the project specific config file
  xsl_params:
    fig_location: http://server.unl.edu/data_images/projects/example/figures/
    file_location: http://server.unl.edu/data/projects/
    figures: true
    fw: true        # form works (page nums, etc)
    pb: true        # page breaks
    project: full_name_of_project
    slug: short_name_of_project

##################
#   Production   #
##################
production:
  # solr information
  solr_path: http://server.unl.edu:port/solr/
  solr_core: name_of_core

  # NOTE! If you are altering ANY of the xsl_params you must
  #   copy over ALL of them to the project specific config file
  xsl_params:
    fig_location: http://server.unl.edu/data_images/projects/example/figures/
    file_location: http://server.unl.edu/data/projects/
    figures: true
    fw: true        # form works (page nums, etc)
    pb: true        # page breaks
    project: full_name_of_project
    slug: short_name_of_project
