default:
  threads: 5
  es_path: http://localhost:9200
  # Note: override es_index as necessary per project / environment
  # in order to push to API vs project testing index, etc
  # this is NOT the "type" of an elasticsearch index
  es_index: test1

###################
#   Development   #
###################

development:
  # solr information
  solr_path: http://rosie.unl.edu:8080/solr/

##################
#   Production   #
##################
production:
  # solr information
  solr_path: http://cdrhsearch.unl.edu:8080/solr/
