# This config file should be copied and added at  projects/<project_name>/config/config.yml
# This config file is specific to each project
# It automatically uses the general configuration file options unless overridden here

development:
    solr_core: name_of_core
    # you can optionally override things from the general config file
    # tei_xsl: projects/name_of_project/scripts/xslt/solr_transform_tei.xsl
    # solr_path: new/path/to/solr/url
production:
    solr_core: name_of_core