# This config file should be copied and added at  projects/<project_name>/config/config.yml
# It should be specific to each project

# The name of the core, not the path to the core
# TODO if the names are different on test and production this code will need to be changed
solr_core: name_of_core

fig_location: http://rosie.unl.edu/data_images/projects/example/figures/

# XSL Options
xslt:
  figures: true
  fw: true        # form works (page nums, etc)
  pb: true        # page breaks
  project: full_name_of_project
  slug: short_name_of_project