# This config file should be copied and added at  projects/<project_name>/config/config.yml
# This config file is specific to each project
# It automatically uses the general configuration file options unless overridden here

development:
    solr_core: name_of_core
production:
    solr_core: name_of_core