# This config file should be copied and added at  projects/<project_name>/config/config.yml
# It should be specific to each project

# The name of the core, not the path to the core
# TODO if the names are different on test and production this code will need to be changed
solr_core: name_of_core

fig_location: location_of_figures_per_project
keyword_link: unknown
# TODO this should probably be specific to test and production
site_location: base_url

# XSL Options
metadata_box: DELETE
figures: true
fw: true
pb: true
project: full_name_of_project
slug: short_name_of_project

# This might be a good way to put the url into the xslt as a param
development:
  base_url: rosie.unl.edu/test_site
production:
  base_url: test_site.unl.edu
