default:
  shortname: example
  collection_desc: Example Data Repository
  es_type: example
  solr_core: there_is_no_solr_core

  variables_html:
    fig_location: some/path
    figures: true
    fw: true
    pb: true
# development:
  # development overrides here
# production:
  # production overrides here
