default:
  shortname: example
  # the directory name will be used if collection is omitted here
  collection: example
  collection_desc: Example Data Repository
  solr_core: there_is_no_solr_core

  variables_html:
    image_large: 800
    image_thumb: 150
# development:
  # development overrides here
# production:
  # production overrides here
