default:
  shortname: example
  project_desc: Example Data Repository
  variables_html:
    fig_location: some/path
    figures: true
    fw: true
    pb: true
  variables_search:
    file_location: some/path
